#!/bin/bash
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_base $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qpoint $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qpointf $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qline_1 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qline_2 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qline_3 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qline_4 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qline_5 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qline_6 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qline_7 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qlinef_1 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qlinef_2 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qlinef_3 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qlinef_4 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qlinef_5 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qlinef_6 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qlinef_7 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_1 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_2 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_3 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_4 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_5 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_6 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_7 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_8 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtri_9 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_1 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_2 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_3 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_4 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_5 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_6 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_7 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_8 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qtrif_9 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_1 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_2 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_3 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_4 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_5 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_6 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_7 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_8 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrect_9 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_1 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_2 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_3 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_4 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_5 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_6 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_7 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_8 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qrectf_9 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_1 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_2 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_3 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_4 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_5 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_6 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_7 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_8 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipse_9 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_1 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_2 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_3 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_4 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_5 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_6 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_7 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_8 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_qtshapes_qellipsef_9 $@
/home/hsherief/gasandbox/ZGLshapes/tests/test_z_linalg $@
